language: python
sudo: false

cache: pip

matrix:
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7-dev"
      env: TOXENV=py37
    - python: "3.6"
      env: TOXENV=docs

install:
- virtualenv --version
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version
script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_failure: always
  pushover:
    users:
    - secure: "ZSM4Rfh94ImAz9NpSSIAASm2NYl67knsbWB658Ez5lfEt9toRV0hG4syKD14j5METphzMA+q3GlcU8Ob9pSk17IsBI3KWGHeOOf9pFYvgHvzsg970feoVcnB67wAvMO7PZjWbS+cHBjXl/3NbEUy9D9qwOwnxKYlnha123PPegDpPZrXTR718rLq658ZQ5/bUMEeeJ5LZcRY7uXAtVDNo70H8yHHz+WFrW8hjeYDjcUmurOj72I2iFTwUcdrEKpCgOnE5Xn1rKuVnGHUO1JFq6GnSXGnyFqvu2FhInF8ROMJO1BSIL7lbcPZBTTsuegCHyVEB0EB/xp41KHitW8HlcTn2L2gC769fORpqa0+KqkPnQLcBYGkThRhRA+/gfSEhGL+3cioMMFOtgpBQmjsERgZ9rHpAVzlCPtwW8jjpb9B+pfoJpzrrb10p0QbrSFatLJ8/0e4taO8cfcyI3oiio9VkexUWC0bddpz7giUQcvy3uJKYGhOtQS56zObA4dWFZLCdAIHirlWoJjsE2X2Jl5L35Xt5uODyunQkEld8DJ9+Rf0HZUTY+wz+KwyLG7bAnIeIawvacddguoxGpuAYJb6+E9V062siyTdLpIdlXUH4eP/itcM2bFdOzoCupr/2IKaPJbNqjyTQxbDL9O3F61Ie5EDNUrutpcmJ+1KVAs="
    api_key:
      secure: "pWDm0+uqV93aluGy+32Au+8VhfyGxc5KGo1ol36m4W6h8J34wtiCXxAL0dXXXwLTYoI1RWV70ZkjSf6QrKNMdVsulU3klBqo5Zzd5iFZca+B90IidgWGP9VP26/+ZqCxTyFwBx8mTjr7tP3VCxSSJRn4lzmZPl7k5GjlMExKkHKT2XeN7PIahfVACdggO4hhhc8BovdDrxsQx0kRYYe4Stlk24ua4o45MXvdOumlDtqeshHrnz50IK/Q7EhJamV0flB694DsxqgukITGiTcU7+IvRAkj72UJ+gZty5v5WKICdhMySFw28mKiDZxV6zOhGt2pWVx5tonZJN/osQtLB41U0PY+/sY8GIwHa5ITNz0V7XSWhpBKha4+1HYgp2g0ZAexSsQJ1nfeVuxyLcxCfc6XcVDxg0JcvQGzpgOWz8QNSiVLdEZ50veKuN166FCzq3CQiJsmNk1n6Cehbcu3imxj+RcVALQASVnRO5eG8Ki+aRggYhVorTWlalceaJiKOpvpeCErhOxNbtDQXHnovfsT5du2VMVSOF2hruzuUMlijIqFkcO4gq6x/BLSZe/1wds8L27vvrxYaUUsmwHfylxl8Hbzp+gU4Wk7LNf9lc6nyLRq1vn+CqQO0RfBRSFtWE4sLX7VyiR4TV7URvihOUbeYaOnOOs6t/PBrX8WQvQ="
branches:
  except:
    - "/^noci-.*$/"
